@echo off
:loop
taskkill /f /im cloudmusic.exe >nul 2>&1
taskkill /f /im neteasecloudmusic.exe >nul 2>&1
taskkill /f /im qqmusic.exe >nul 2>&1
taskkill /f /im kugou.exe >nul 2>&1
taskkill /f /im kuwo.exe >nul 2>&1
taskkill /f /im migu.exe >nul 2>&1
taskkill /f /im spotify.exe >nul 2>&1
taskkill /f /im bilibili.exe >nul 2>&1
taskkill /f /im iqiyi.exe >nul 2>&1
taskkill /f /im youku.exe >nul 2>&1
taskkill /f /im tencentvideo.exe >nul 2>&1
taskkill /f /im mgtv.exe >nul 2>&1
taskkill /f /im ppstream.exe >nul 2>&1
taskkill /f /im pptv.exe >nul 2>&1
taskkill /f /im baofeng.exe >nul 2>&1
taskkill /f /im tudou.exe >nul 2>&1
taskkill /f /im letv.exe >nul 2>&1
taskkill /f /im acfun.exe >nul 2>&1
taskkill /f /im douyin.exe >nul 2>&1
taskkill /f /im kuaishou.exe >nul 2>&1
taskkill /f /im weishi.exe >nul 2>&1
taskkill /f /im huya.exe >nul 2>&1
taskkill /f /im douyu.exe >nul 2>&1
taskkill /f /im yy.exe >nul 2>&1
taskkill /f /im yylive.exe >nul 2>&1
taskkill /f /im ximalaya.exe >nul 2>&1
taskkill /f /im lizhi.exe >nul 2>&1
taskkill /f /im qingting.exe >nul 2>&1
taskkill /f /im netease_music_core.exe >nul 2>&1
taskkill /f /im kugou8.exe >nul 2>&1
taskkill /f /im kwmusic.exe >nul 2>&1
taskkill /f /im yinyuetai.exe >nul 2>&1
taskkill /f /im xiami.exe >nul 2>&1
taskkill /f /im qqplayer.exe >nul 2>&1
taskkill /f /im kmp.exe >nul 2>&1
taskkill /f /im xunlei.exe >nul 2>&1
taskkill /f /im thunder.exe >nul 2>&1
taskkill /f /im xmp.exe >nul 2>&1
taskkill /f /im qvodplayer.exe >nul 2>&1
taskkill /f /im qvod.exe >nul 2>&1
taskkill /f /im rayfile.exe >nul 2>&1
taskkill /f /im funshion.exe >nul 2>&1
taskkill /f /im 风行视频.exe >nul 2>&1
taskkill /f /im fengxing.exe >nul 2>&1
taskkill /f /im qqlive.exe >nul 2>&1
taskkill /f /im qqvideo.exe >nul 2>&1
taskkill /f /im sohuvideo.exe >nul 2>&1
taskkill /f /im sogouvideo.exe >nul 2>&1
taskkill /f /im 56video.exe >nul 2>&1
taskkill /f /im ku6.exe >nul 2>&1
taskkill /f /im xunleikankan.exe >nul 2>&1
taskkill /f /im kankan.exe >nul 2>&1
taskkill /f /im baiduvideo.exe >nul 2>&1
taskkill /f /im bdvideoplayer.exe >nul 2>&1
taskkill /f /im sogoumusic.exe >nul 2>&1
taskkill /f /im baidumusic.exe >nul 2>&1
taskkill /f /im duomi.exe >nul 2>&1
taskkill /f /im jingdongmusic.exe >nul 2>&1
taskkill /f /im taobaomusic.exe >nul 2>&1
taskkill /f /im alimusic.exe >nul 2>&1
taskkill /f /im ttmusic.exe >nul 2>&1
taskkill /f /im 9sky.exe >nul 2>&1
taskkill /f /im a8music.exe >nul 2>&1
taskkill /f /im concert.exe >nul 2>&1
taskkill /f /im cooldog.exe >nul 2>&1
taskkill /f /im dogmusic.exe >nul 2>&1
taskkill /f /im duowan.exe >nul 2>&1
taskkill /f /im yy8.exe >nul 2>&1
taskkill /f /im yyclient.exe >nul 2>&1
taskkill /f /im huajiao.exe >nul 2>&1
taskkill /f /im ingkee.exe >nul 2>&1
taskkill /f /im miaopai.exe >nul 2>&1
taskkill /f /im meipai.exe >nul 2>&1
taskkill /f /im xiaoying.exe >nul 2>&1
taskkill /f /im meitu.exe >nul 2>&1
taskkill /f /im toutiao.exe >nul 2>&1
taskkill /f /im newsarticle.exe >nul 2>&1
taskkill /f /im tencentnews.exe >nul 2>&1
taskkill /f /im sinanews.exe >nul 2>&1
taskkill /f /im neteasenews.exe >nul 2>&1
taskkill /f /im iqiyinews.exe >nul 2>&1
taskkill /f /im kuaibao.exe >nul 2>&1
taskkill /f /im weibo.exe >nul 2>&1
taskkill /f /im qqweibo.exe >nul 2>&1
taskkill /f /im sinaweibo.exe >nul 2>&1
taskkill /f /im tencentweibo.exe >nul 2>&1
taskkill /f /im renren.exe >nul 2>&1
taskkill /f /im kaixin.exe >nul 2>&1
taskkill /f /im pengyou.exe >nul 2>&1
taskkill /f /im qqzone.exe >nul 2>&1
taskkill /f /im qzone.exe >nul 2>&1
taskkill /f /im tiktok.exe >nul 2>&1
taskkill /f /im musical.ly.exe >nul 2>&1
taskkill /f /im kwai.exe >nul 2>&1
taskkill /f /im likee.exe >nul 2>&1
taskkill /f /im vibe.exe >nul 2>&1
taskkill /f /im snapchat.exe >nul 2>&1
taskkill /f /im instagram.exe >nul 2>&1
taskkill /f /im facebook.exe >nul 2>&1
taskkill /f /im twitter.exe >nul 2>&1
taskkill /f /im youtube.exe >nul 2>&1
taskkill /f /im netflix.exe >nul 2>&1
taskkill /f /im hulu.exe >nul 2>&1
taskkill /f /im disneyplus.exe >nul 2>&1
taskkill /f /im hbo.exe >nul 2>&1
taskkill /f /im primevideo.exe >nul 2>&1
taskkill /f /im applemusic.exe >nul 2>&1
taskkill /f /im appletv.exe >nul 2>&1
taskkill /f /im youtubemusic.exe >nul 2>&1
taskkill /f /im pandora.exe >nul 2>&1
taskkill /f /im soundcloud.exe >nul 2>&1
taskkill /f /im deezer.exe >nul 2>&1
taskkill /f /im tidal.exe >nul 2>&1
taskkill /f /im napster.exe >nul 2>&1
taskkill /f /im gaana.exe >nul 2>&1
taskkill /f /im saavn.exe >nul 2>&1
taskkill /f /im joox.exe >nul 2>&1
taskkill /f /im anghami.exe >nul 2>&1
taskkill /f /im kkbox.exe >nul 2>&1
taskkill /f /im jiosaavn.exe >nul 2>&1
taskkill /f /im wynk.exe >nul 2>&1
taskkill /f /im hungama.exe >nul 2>&1
taskkill /f /im rhapsody.exe >nul 2>&1
taskkill /f /im lastfm.exe >nul 2>&1
taskkill /f /im mixcloud.exe >nul 2>&1
taskkill /f /im tunein.exe >nul 2>&1
taskkill /f /im iheartradio.exe >nul 2>&1
taskkill /f /im slacker.exe >nul 2>&1
taskkill /f /im jango.exe >nul 2>&1
taskkill /f /im accuradio.exe >nul 2>&1
taskkill /f /im radiotuna.exe >nul 2>&1
taskkill /f /im live365.exe >nul 2>&1
taskkill /f /im streema.exe >nul 2>&1
taskkill /f /im radio.exe >nul 2>&1
timeout /t 1 >nul
goto loop